INSERT INTO PACIENTES(NOME, TIPO_SANGUINEO, DATA_NASCIMENTO, CONVENIO) VALUES ('LUIZ FRANCISCO DE CAMARGO', 'AB-', '2004-09-03', 'SIM');
INSERT INTO PACIENTES(NOME, TIPO_SANGUINEO, DATA_NASCIMENTO, CONVENIO) VALUES ('LAIS BOESING', 'A-', '2004-07-28', 'SIM');
INSERT INTO PACIENTES(NOME, TIPO_SANGUINEO, DATA_NASCIMENTO, CONVENIO) VALUES ('NALANDA HOFMAN', 'B-', '2004-01-31', 'NAO');