INSERT INTO CONSULTAS(MOTIVO_CONSULTA, DATA_CONSULTA, HORARIO_CONSULTA, PACIENTE) VALUES ('DOR DE DENTE', '2024-05-10', '08:30', 1);
INSERT INTO CONSULTAS(MOTIVO_CONSULTA, DATA_CONSULTA, HORARIO_CONSULTA, PACIENTE) VALUES ('FICOU CEGO', '2024-05-11', '09:30', 2);
INSERT INTO CONSULTAS(MOTIVO_CONSULTA, DATA_CONSULTA, HORARIO_CONSULTA, PACIENTE) VALUES ('QUEBROU O BRAÇO', '2024-05-11', '10:30', 3);